#!/bin/bash
# Set locale to ensure day names are in English
export LC_TIME=C.UTF-8

file_name='TimeTracker'
institution='University of Oulu'
faculty='Faculty of Science'
division='Nano and Molecular Systems Research Unit'
name='Postdoctoral Researcher: Rengel Cane E. Sia'
prof='Line Manager: Dr. Matti Silveri'

# Create log directory if it doesn't exist
mkdir -p "${HOME}/logs"
cd "${HOME}/logs" || exit 1
log_file="${HOME}/logs/${file_name}_$(date +"%Y_%m").log"

signature="__________



$(date '+%Y/%m/%d')
_________________________________                                       _________________________________
Date and Signature of Postdoc Fellow                                    Date and Signature of Supervisor"

touch "$log_file"

#Activity
echo "please select activity:
1. lectures
2. teaching
3. research
4. seminars|workshops|conferences
5. holiday"

# Add a prompt for the user
echo -n "selected number : "
read -r act
case "$act" in
	1) activity='lecture' ;;
	2) activity='teaching' ;;
	3) activity='research' ;;
	4) activity='seminar|workshop|conference' ;;
	5) activity='HOLIDAY' ;;
	*)
		echo "you have chosen an incorrect option"
		activity='unidentified'
		echo "activity: $activity"
		exit 1
		;;
esac
echo "activity: $activity"

################# HEADER #####################
if ! [[ -s "$log_file" ]]; then
	echo "First working day of the month: $(date '+%Y.%m.%d @ %H:%M:%S')"
	{
		echo "$institution"
		echo "$faculty"
		echo "$division"
		echo
		echo "$name"
		echo "$prof"
		echo "__________"
		echo
		echo "$(date +"%A") Activity: $activity"
		echo "log-in  : $(date '+%Y.%m.%d @ %H:%M:%S')"
		echo "log-out : $(date '+%Y.%m.%d @ %H:%M:%S')"
		echo "elapsed_time: 0hrs,0mins,0secs"
	} >> "$log_file"
	echo "log file created: $log_file"
	echo "elapsed_time: 0hrs,0mins,0secs"
else
	# Get the last line from the log file
	ll=$(tail -n 1 "$log_file")
fi

ll=$(tail -n 1 "$log_file")
rl="${ll%% *}"

#echo "rl: "$rl""
if [[ "$rl" == "Date" ]];then
	sed -i "$(($(wc -l < "$log_file")-9)),\$d" "$log_file"
	ll=$( tail -n 1 "$log_file" )
	echo last line after removing date lines: "$ll"
fi

if [[ "$rl" == "elapsed_time:" ]];then
	# Remove the last line if it contains elapsed_time
	ll=$(cat ./"$file_name"_"$(date +"%Y_%m").log" | tail -3 | head -1 )
	#sed -i "$(($(wc -l < "$log_file")-1)),\$d" "$log_file"
	#ll=$( tail -n 1 "$log_file" )
	echo last line after removing elapsed time lines: "$ll"
fi

#ll=$(tail -n 1 "$log_file")
echo "ll: $ll"
rl="${ll%% *}"
echo "rl: $rl"
#ll=$(tail -n 1 "$log_file")
echo "ll: $ll"
sl=${ll#*log-in : }
echo "sl: $sl"
fulldate=${sl#*: }
echo "full date: $fulldate"
idate=${fulldate%% *}
echo "idate: $idate"
itime=${fulldate#*@ }
iday=${idate#*.*.}
echo "iday: $iday"
fday=`date '+%d'`
echo "today: "$fday""
itime=$(date -d "$itime" "+%s")
ftime="`date '+%H:%M:%S'`"
ftime=$(date -d "$ftime" "+%s")	
dtime=$((ftime-itime))
hrs=$((dtime / 3600))
min=$(((dtime % 3600) / 60))
sec=$((dtime % 60))
n_hours="${hrs}hrs,${min}mins,${sec}secs"
echo n_hours: "$n_hours"
#n_hours="$hrs""hrs,""$min""mins,""$sec""secs"
#echo "itime: $itime"
#echo "ftime: $ftime"
echo "logged at date: "`date '+%Y.%m.%d @ %H:%M:%S'`""

ll=$( tail -n 1 "$log_file" )
rl="${ll%% *}"

if [[ "$iday" = "$fday" ]];then
	if [[ "$rl" == "elapsed_time:" ]];then
		sed -i "$(($(wc -l < "$log_file")-1)),\$d" "$log_file"
	fi
	echo "log-out : "`date '+%Y.%m.%d @ %H:%M:%S'`"" >> "$log_file"
	echo "elapsed_time: ""$n_hours" >> "$log_file"
	echo "you have spent "$n_hours" on $activity"
else
	echo "
`date +"%A"` Activity: $activity
"log-in  : "`date '+%Y.%m.%d @ %H:%M:%S'`""" >> "$log_file"
	echo "log-out : "`date '+%Y.%m.%d @ %H:%M:%S'`"" >> "$log_file"
	echo "elapsed_time: ""0hrs,0mins,0secs" >> "$log_file"
	echo "you have spent 0hrs,0mins,0secs on $activity"
fi

# Today's date
today=$(date +%Y-%m-%d)
# Find the last weekday of the current month
last_date=$(date -d "$(date +%Y-%m-01) +1 month -1 day" +%Y-%m-%d)
while :; do
    dow=$(date -d "$last_date" +%u)  # 1=Mon, ..., 5=Fri, 6=Sat, 7=Sun
    if [[ $dow -ge 1 && $dow -le 5 ]]; then
        last_weekday=$last_date
        break
    fi
    last_date=$(date -I -d "$last_date -1 day")
done
echo "last weekday of the month: $last_weekday"

# Check if today is the last weekday
if [[ "$today" == "$last_weekday" ]]; then
    echo "$signature" >> "$log_file"
fi
# Check if the log file is empty
if [[ ! -s "$log_file" ]]; then
	echo "Log file is empty. Please check the script."
	exit 1
fi
